# Generated by Django 3.0.5 on 2022-05-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_address', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=50)),
                ('providing_services', models.CharField(max_length=50)),
                ('service_benifits', models.CharField(max_length=100)),
                ('sp_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField()),
                ('a_time', models.CharField(max_length=50)),
                ('a_cost', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Customer')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services')),
            ],
        ),
    ]
